### ISSUE TITLE
Not random 

### ISSUE THREAD

**Issue by yasserdastani** [Ramotion/navigation-toolbar-android#14]
Hi . Please provide some tablayout on how to set a specific item for each tablayout. Thanks

**Comment by golovin47** [comment]
Hi, @yasserdastani. If you want to apply some changes to views, best way to see how it can be done is by running sample apps from this repo. If you need some specific features, which this lib doesn't support, you may fork it and add anything you need.

**Comment by yasserdastani** [comment]
Hi. I think I couldn't get my point across.
The program contains a piece of code that arranges arrays in random order in each tab. I want to arrange a certain number of arrays in each tab. Can you help?

**Comment by IvanGolovinYH** [comment]
@yasserdastani You can modify a piece of code that arranges arrays in random order in each tab to work as you want.

**Comment by golovin47** [comment]
@yasserdastani You can modify a piece of code that arranges arrays in random order in each tab to work as you need.
