### ISSUE TITLE
Run time Error while launching it

### ISSUE THREAD

**Issue by subh2020** [Ramotion/navigation-toolbar-android#4]
Hi
I am facing a problem when I try to launch it after building.
[Error_Runtime.txt](https://github.com/Ramotion/navigation-toolbar-android/files/1955044/Error_Runtime.txt)

Please advise on how to fix it.
Thanks
Subh

**Comment by golovin47** [comment]
Hello, subh2020.

We have updated the library, so there shouldn't be any compile/runtime errors.
