### ISSUE TITLE
Title and line display bug

### ISSUE THREAD

**Issue by tchigher** [Ramotion/navigation-toolbar-android#7]
As you can see from the screenshots.
![screenshot_1526613822](https://user-images.githubusercontent.com/34847046/40214557-0d1b88d6-5a8e-11e8-82b2-9f3e008412f9.png)
![screenshot_1526613813](https://user-images.githubusercontent.com/34847046/40214558-0d5aa566-5a8e-11e8-90cc-dbf833cb21f3.png)
![screenshot_1526613760](https://user-images.githubusercontent.com/34847046/40214559-0d955544-5a8e-11e8-8bb0-73253a7746b7.png)

It's just so strange. I spent a night and still cannot find the reason.

**Comment by VinceGee** [comment]
I'm having the same problem, @wangpengwen did you find a solution to this?

**Comment by MissOrnela** [comment]
I have the same issue.Did anyone find the solution please .I have already spent more than one week on this .
Thank

**Comment by golovin47** [comment]
Hello, @MissOrnela, @VinceGee, @wangpengwen. This issue has just been resolved.
