### ISSUE TITLE
Title overlapping 

### ISSUE THREAD

**Issue by BilalSiddiqui** [Ramotion/navigation-toolbar-android#8]
Click on any tab from list and and fling up and down continuously. See the header with overlapped titles 
![screenshot_20181126-021725_meera](https://user-images.githubusercontent.com/1955553/48984780-0c291080-f122-11e8-90aa-bcf485f2a464.jpg)
![screenshot_20181126-021714_meera](https://user-images.githubusercontent.com/1955553/48984781-0c291080-f122-11e8-82dd-f099aa5da2c7.jpg)

**Comment by MissOrnela** [comment]
hello i have the same issue
Please did you already solve it ?

**Comment by golovin47** [comment]
Hello, @MissOrnela, @BilalSiddiqui. This issue has just been resolved.
